[Settings]
# Dark theme for all GTK3 applications
gtk-application-prefer-dark = true
gtk-theme-name = Arc-Dark
gtk-icon-theme-name = Papirus-Dark
gtk-font-name = Sans 10
gtk-cursor-theme-name = default
